### ISSUE TITLE
Add time_units to the y-axis labels

### ISSUE THREAD

**Issue by hyanwong** [tskit-dev/tsbrowse#125] opened 2024-02-06 17:26 UTC
Most tree sequences now have a `time_units` attribute. It should be really easy to add this in brackets to any axis labels that say "Time xxx", e.g. "Time of parent node" would become "Time of parent node (generations)".

**Comment by benjeffery** [comment] 2024-10-14 15:41
Dupe of #83

**Closed by benjeffery** 2024-10-14 15:41 UTC
